"""Sprint 5 — FastAPI inference server.

All configuration is via environment variables so the same image works in
local dev, staging, and prod without code changes.

Environment variables:
  OUTPUT_DIR      : directory containing pre-generated output files (default: outputs)
  BASE_DATA_FILE  : override path to base workbook
  CLAIMS_DATA_FILE: override path to claims workbook
  CACHE_DIR       : override path to feature-table cache

Endpoints:
  GET  /health    : liveness probe
  GET  /metrics   : latest Track 3 metrics JSON
  POST /triage    : run (or re-run) the full triage pipeline
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

try:
    from fastapi import FastAPI, HTTPException
    from fastapi.middleware.cors import CORSMiddleware
    from pydantic import BaseModel, Field
    _FASTAPI_AVAILABLE = True
except ImportError:
    _FASTAPI_AVAILABLE = False
    logger.warning("fastapi not installed — API server will not start. Run: pip install fastapi uvicorn")
    # Provide stubs so the module still imports cleanly
    class FastAPI:  # type: ignore[no-redef]
        def get(self, *a, **k): return lambda f: f
        def post(self, *a, **k): return lambda f: f
        def add_middleware(self, *a, **k): pass
    class BaseModel: pass  # type: ignore[no-redef]
    class HTTPException(Exception): pass  # type: ignore[no-redef]
    class Field:  # type: ignore[no-redef]
        def __new__(cls, *a, **k): return None
    class CORSMiddleware: pass  # type: ignore[no-redef]


OUTPUT_DIR = Path(os.environ.get("OUTPUT_DIR", "outputs"))
TRACK3_METRICS_PATH = OUTPUT_DIR / "track3" / "track3_metrics.json"
TRACK2_METRICS_PATH = OUTPUT_DIR / "track2" / "track2_cv_metrics.json"
TRACK1_METRICS_PATH = OUTPUT_DIR / "track1" / "track1_overview.json"

app = FastAPI(
    title="R3 Hackathon Triage API",
    description="Provider directory verification — passive correction + call triage",
    version="1.0.0",
)

if _FASTAPI_AVAILABLE:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )


class TriageRequest(BaseModel):
    n_calls: int = Field(default=450, ge=1, le=450, description="Call budget (hard cap 450)")
    alpha: float = Field(default=0.05, ge=0.01, le=0.20, description="Conformal miscoverage rate")
    use_cache: bool = Field(default=True, description="Use parquet feature cache if available")


class PredictRequest(BaseModel):
    """Judge-spec predict endpoint payload.

    Either provide `data` (list of records matching the base workbook columns) OR
    leave empty to use the most recent training run's predictions.
    """
    data: list[dict] = Field(default_factory=list, description="List of records to predict on")
    n_calls: int = Field(default=450, ge=0, le=450, description="Robocall budget (hard cap 450)")
    alpha: float = Field(default=0.05, ge=0.01, le=0.20, description="Conformal miscoverage rate")


class HealthResponse(BaseModel):
    status: str
    outputs_exist: bool
    metrics_file_exists: bool


@app.get("/health", response_model=HealthResponse)
def health() -> dict[str, Any]:
    """Liveness probe — always returns 200 if the server is running."""
    return {
        "status": "ok",
        "outputs_exist": OUTPUT_DIR.exists(),
        "metrics_file_exists": TRACK3_METRICS_PATH.exists(),
    }


@app.get("/metrics")
def metrics() -> dict[str, Any]:
    """Return the latest Track 3 metrics JSON (generated by run_track3.py)."""
    if not TRACK3_METRICS_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Metrics file not found at {TRACK3_METRICS_PATH}. Run scripts/run_track3.py first.",
        )
    return json.loads(TRACK3_METRICS_PATH.read_text())


@app.get("/metrics/all")
def all_metrics() -> dict[str, Any]:
    """Return combined metrics from all three tracks."""
    result: dict[str, Any] = {}
    for label, path in [
        ("track1", TRACK1_METRICS_PATH),
        ("track2", TRACK2_METRICS_PATH),
        ("track3", TRACK3_METRICS_PATH),
    ]:
        if path.exists():
            result[label] = json.loads(path.read_text())
        else:
            result[label] = {"error": f"not found — run scripts/run_{label}.py first"}
    return result


@app.post("/triage")
def triage(req: TriageRequest) -> dict[str, Any]:
    """Run the full triage pipeline and return the top-N call targets.

    This re-runs Track 2 + Track 3 end-to-end (which takes ~2–5 minutes on
    the hackathon dataset).  For low-latency demos, call GET /metrics instead.
    """
    try:
        # Import here to avoid loading heavy deps at startup if not needed
        import os as _os
        if req.use_cache:
            _os.environ.setdefault("CACHE_DIR", str(OUTPUT_DIR / "cache"))

        from r3hackathon.track3 import run_track3

        out_dir = OUTPUT_DIR / "track3"
        result = run_track3(out_dir, n_calls=req.n_calls, alpha=req.alpha)

        top_calls = result["top_calls"]
        metrics_out = result["metrics"]

        # Return JSON-serialisable dict
        top_call_columns = [
            c for c in [
                "Row ID", "OrganizationName", "triage_score", "triage_score_lgb", "p_r3_wrong",
                "p_conclusive_rank", "business_gain", "triage_reason_codes",
                "conformal_uncertain", "address_staleness_score"
            ]
            if c in top_calls.columns
        ]
        return {
            "metrics": metrics_out,
            "top_calls": top_calls[top_call_columns].to_dict(orient="records"),
            "conformal_meta": result.get("conformal_meta", {}),
        }
    except Exception as exc:
        logger.exception("Triage pipeline failed")
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/predict")
def predict(req: PredictRequest) -> dict[str, Any]:
    """Judge-spec predict endpoint.

    Returns predictions in the required schema:
        record_id | final_prediction | confidence | action_taken

    Where action_taken ∈ {"R3_ACCEPT", "OVERRIDE", "ROBOCALL"}.

    If `data` is empty, returns predictions from the latest training run
    (outputs/track3/track3_full_ranking.csv). Otherwise applies the trained
    Track 2 + Track 3 models to the supplied records.
    """
    try:
        import pandas as pd
        import sys
        sys.path.insert(0, "src")
        from scripts.generate_submission import build_submission  # type: ignore

        ranking_path = OUTPUT_DIR / "track3" / "track3_full_ranking.csv"

        if not req.data:
            # Use cached training predictions
            if not ranking_path.exists():
                raise HTTPException(
                    status_code=404,
                    detail=f"No cached predictions at {ranking_path}. Run scripts/run_track3.py or POST data."
                )
            ranking = pd.read_csv(ranking_path)
        else:
            # Live inference on the supplied data
            import pickle
            from r3hackathon.features import engineer_base_features, merge_claim_features
            from r3hackathon.track2 import score_passive_models, apply_passive_rules
            from r3hackathon.track3 import (
                fit_conclusive_model, score_conclusive_model, add_triage_features,
                fit_conformal_calibration, conformal_select,
            )
            import numpy as np

            base_df = pd.DataFrame(req.data)
            featured = engineer_base_features(base_df)
            # Without claims, downstream features are NaN-tolerant
            from r3hackathon.features import _ensure_claim_columns
            scored_input = _ensure_claim_columns(featured) if hasattr(_ensure_claim_columns, "__call__") else featured

            # Load trained Track 2 models
            t2_pkl = OUTPUT_DIR / "track2" / "track2_models.pkl"
            if not t2_pkl.exists():
                raise HTTPException(status_code=503, detail=f"Track 2 models not found at {t2_pkl}")
            with open(t2_pkl, "rb") as f:
                t2_models = pickle.load(f)

            t2_meta = json.loads((OUTPUT_DIR / "track2" / "track2_metadata.json").read_text())
            scored = score_passive_models(featured, t2_models)
            scored.attrs["q_hat"] = t2_meta["q_hat_full"]
            t2_pred = apply_passive_rules(scored)

            cm = fit_conclusive_model(t2_pred)
            t3_df = score_conclusive_model(t2_pred, cm)
            t3_df = add_triage_features(t3_df)

            p_raw = t3_df["p_r3_wrong"].fillna(0.0).values
            cand = t3_df["needs_active_review"].fillna(False).values
            calib_mask = cand if cand.sum() >= 10 else np.ones(len(t3_df), dtype=bool)
            zero_labels = np.zeros(len(t3_df), dtype=int)
            p_cal, _, _ = fit_conformal_calibration(p_raw, zero_labels, calib_mask, alpha=req.alpha)

            t3_meta = json.loads((OUTPUT_DIR / "track3" / "track3_metrics.json").read_text())
            lambda_hat = t3_meta.get("conformal_lambda_hat", 0.735)

            score_col = "triage_score"
            t3_pkl = OUTPUT_DIR / "track3" / "track3_ranker.pkl"
            if t3_pkl.exists():
                with open(t3_pkl, "rb") as f:
                    ranker = pickle.load(f)
                X = t3_df.reindex(columns=ranker["feature_cols"]).fillna(0.0)
                try:
                    t3_df["triage_score_lgb"] = ranker["lgb_model"].predict(X)
                    score_col = "triage_score_lgb"
                except Exception as exc:
                    logger.warning(f"LGB predict failed: {exc}")

            ranking, _ = conformal_select(
                t3_df, p_cal, lambda_hat,
                n_calls=req.n_calls, gain_col="business_gain",
                score_col=score_col, alpha=req.alpha,
            )

        submission = build_submission(ranking)
        return {
            "n": int(len(submission)),
            "action_breakdown": submission["action_taken"].value_counts().to_dict(),
            "predictions": submission.head(req.n_calls + 1000).to_dict(orient="records"),
        }

    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Predict failed")
        raise HTTPException(status_code=500, detail=str(exc))


if __name__ == "__main__":
    if not _FASTAPI_AVAILABLE:
        print("Install fastapi and uvicorn first:  pip install fastapi uvicorn")
    else:
        import uvicorn
        uvicorn.run(
            "main:app",
            host=os.environ.get("HOST", "0.0.0.0"),
            port=int(os.environ.get("PORT", "8000")),
            reload=os.environ.get("RELOAD", "false").lower() == "true",
        )
